### ISSUE TITLE
Upgrade Fails

### ISSUE THREAD

**Issue by xeu100** [YunoHost-Apps/gitlab_ynh#111] opened 2020-05-12 01:05 UTC
No information was seen except for the logs:

https://paste.yunohost.org/raw/gilifaseye

**Comment by kay0u** [comment] 2020-05-12 08:33
Hi!

Thank you for your report and sorry for the inconvenience, there is a bug in the update script. I will fix it as soon as possible.

**Comment by laudeon** [comment] 2020-05-13 16:16
Hi,

Thanks for the work!

I have been into the same issue. Yunohost told me that it restored gitlab app as it was before. So that's cool.

Since then, each time I try to go on gitlab it gets me to the reset password page. To be more precise, at this URL : `https://git.domain.com/users/password/edit?reset_password_token=*******`.

I have tried several things like accessing it being logged in with my Yunohost user account and without being logged in. I tried in different browsers as well. I also tried to see if it was related to #91. But apparently not.

I have looked at the error and access logs, I have not seen anything helping understanding what is happening. Nothing popping in error.log and in access.log I can see these redirection pattern : 
```
[13/May/2020:18:05:33 +0200] "GET / HTTP/2.0" 302 754 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
[13/May/2020:18:05:33 +0200] "GET /users/sign_in HTTP/2.0" 302 818 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
[13/May/2020:18:05:33 +0200] "GET /users/password/edit?reset_password_token=x8cEXLHEZZHoZwxzLPaa HTTP/2.0" 200 10410 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
```
So, why not, I tried to reset my password as it is asked. But nothing seems to work : missing email, username, etc. So I assume it does not pass through the SSO?

Any thoughts?

Thanks!

**Comment by kay0u** [comment] 2020-05-13 18:22
Strange, I can't reproduce your issue.

Naively, I would:

- Try restarting gitlab: `sudo gitlab-ctl restart` (you may see an error 500 for a moment while gitlab restarts)
- Try to restore again with the lastest backup (generated during the upgrade)
- Try something like this: https://docs.gitlab.com/ee/security/reset_root_password.html

**Comment by laudeon** [comment] 2020-05-14 09:13
Hey,

Thanks for the help. So I've tired your suggestions :
- the restart works, but does not fix my issue.
- the backup did not start at all, it tells me that I have already an app with the same "ID". (I might do something wrong here, I'm not really used to backups with yunohost).
- I changed the gitlab's admin pass as they explained in the doc you suggested. Does not fix the problem. I've then tried to restart gitlab. Nope again.

I'm thinking I should reinstall gitlab if I want to be able to use it again :smile: 
Again, thank you for the help on that!

**Comment by kay0u** [comment] 2020-05-14 09:15
> the backup did not start at all, it tells me that I have already an app with the same "ID". (I might do something wrong here, I'm not really used to backups with yunohost).

You must before remove the current app (gitlab here) to be able to restore it :-)

**Comment by laudeon** [comment] 2020-05-14 12:04
So I've done that, the backup worked thanks. 
After the backup gitlab still have the same issue though :/
I'm reinstalling it. Anyway thanks a lot for the help! If I find what was the issue I'll let you know somehow.

**Comment by kay0u** [comment] 2020-05-14 12:10
Thank you for your feedback, and very sorry for the trouble!

**Comment by kay0u** [comment] 2020-05-16 09:45
#112 is merged, you can reopen this issue if needed

**Closed by kay0u** 2020-05-16 09:45 UTC
